### PR TITLE
Embedding MathML and SVG in HTML

### PR DESCRIPTION
**Pull request by jpw**
- adds "Closing elements in embedded documents" section
 - other minor wording and whitespace tweaks

### CODE REVIEW

**Comment by moddular** [comment]
In most of our article/book/chapter content we tend to use TeX rather than MathML for equations, so I'm not entirely sure about it. Though I would suspect given that much of this type of content is generated by an XSL transform on an XML document we'd end up with namespace gubbins and `/>` being output.

The SVG stuff sounds right, though again I'd probably caveat that for places where that comes from some XSLT.

**Comment by jpw** [comment]
Thanks @moddular. I also suspect many instances of this come from XSLT tools. IIRC XSLT tools can be configured to output `html` serialisation but in practice, people tend not to 😞

I suppose SVG tools default to XML serialisation so as to be safe in strict environments (SVG docs) and tend not to worry about embedding in HTML as it "will probably work in browsers because they can mainly handle both serialisations".

**Comment by jpw** [comment]
How did you get on with this in the end @moddular  ?

**Review by moddular — APPROVED** [review]
All sounds good to me. The XSLT has been updated to output an HTML serialisation.

**Pull request merged**
