### PR TITLE
Update node practices document

### PR DESCRIPTION
**Pull request by josebolos**
Renames the file and adds "publishing to npm" and snyk sections. This addresses #121 and #143.

### CODE REVIEW

**Comment by josebolos** [comment]
I see. The choice of words in this particular sentence was intentional. I was using `must` as specified in [RFC 2119](https://www.ietf.org/rfc/rfc2119.txt), which is what we usually do for all our docs, implying that adding the project to Snyk is not optional.

If people think that it's not clear that way I'll change it. Let's see what others think.

**Comment by hollsk** [comment]
"must", "should", "required" etc is consistent with our approach to language throughout

we should really add a link to RFC 2119 somewhere prominent, say on the README itself, or in the house style guides 

it's linked inside individual pages but a bit of tidying would be nice (another PR though)

i still disagree with lowercasing those keywords, fwiw - if we'd continued to uppercase them then it would have been more obvious that this was a requirement level keyword

**Comment by hollsk** [comment]
in fact, it might also be good to add a note about using requirement level keywords to the language guide itself

**Comment by josebolos** [comment]
Addressed in #184.

**Pull request merged**
