### PR TITLE
remove recommendation of Lighthouse

### PR DESCRIPTION
**Pull request by hollsk**
We don't recommend the use of this tool anymore. We have other tools that better fit our needs 🙂 

(rationale in this comment if you want the TL;DR: https://github.com/springernature/frontend-playbook/pull/360#issuecomment-638890182 )

### CODE REVIEW

**Comment by saramorueta** [comment]
out of curiosity. Do you have a document to read about that conclusion? thanks

**Comment by hollsk** [comment]
We're working on an internal document that does just that! Will let you know once it's ready for publication 😅

**Comment by dotcode** [comment]
Would be interesting to have as much as possible in the public domain …

**Comment by hollsk** [comment]
I've reverted the changes to the performance docs due to overreach 😉

**Pull request merged**
