### PR TITLE
Add RFC 2119

### PR DESCRIPTION
**Pull request by hollsk**
Been meaning to add this for quite some time

### CODE REVIEW

**Comment by dotcode** [comment]
One thought … have you trawled every page to ensure they are being used appropriately?

**Comment by hollsk** [comment]
Nah. [RFC 8174](https://tools.ietf.org/html/rfc8174) states that RFC 2119 applies to only those words that are capitalised. 

The safest approach for us would be to allow that any key word that _isn't_ capitalised to have no special meaning, and to only capitalise in those instances where it does.

**Comment by dotcode** [comment]
Wow, didn't know about RFC 8174. My opinion before we've had an in-depth debate where you prove me wrong: I think I dislike it. I've had many a moment in the past where I think "oh God, RFC 2119 applies, now I really have to think about this", to good effect. I also dislike the ambiguity this introduces. I'd rather just RFC 2119 applies, forcing people to properly consider their recommendations. 

How are you going to warp my fragile little mind?

**Comment by hollsk** [comment]
I'm not. I just suggested it to try to get out of trawling the entire Playbook looking for keywords  💁‍♂️

**Comment by jpw** [comment]
My 2p is I dislike it in non-formal documents because it imparts a VERY SHOUTY TONE.

**Comment by danyalaytekin** [comment]
Maybe add a small apology above the new explanatory section, to emphasise the use of capitals is to comply with a convention rather than a result of rage?

**Comment by jpw** [comment]
@danyalaytekin oooh I like that idea a lot, thanks!

**Pull request merged**
