### PR TITLE
adjust ALL the things

### PR DESCRIPTION
**Pull request by hollsk**
BEHOLD! My proposal!

* JS, CSS, and markup get a directory of their own under the root, each of which contains a `house-style.md` along with anything other files related to their overarching theme
* Some of these directories will have lots of files in, some won't. NBD
* Accessibility, git, and general writing guides all get their own directories under root

This leaves the "practices" directory looking like a chum bucket of unrelated concepts 😷 but it's ok because:

* I've created an issue #180 to contain anything perf related
* We already have another issue #143 for general node concepts

What say you?

(here's the proposed tree which is easier to look at than the commit diff: https://github.com/springernature/frontend-playbook/tree/acdb516ed13f3610687ae0cc766a4a8b98177ff1 )

(and here's the issue that prompted all this in the first plaice 🐟 https://github.com/springernature/frontend-open-space/issues/94 [private repo])

### CODE REVIEW

**Comment by davidpauljunior** [comment]
This looks like a good approach to me.  I like that fact that you could pass someone a url that encompasses a language entirely.

**Comment by jpw** [comment]
Nice! Did you check the links didn't break?

**Comment by hollsk** [comment]
I went through every single file and updated every single link that needed updated, but obviously I'd appreciate people clicking about a bit just to make sure 😁

**Comment by hollsk** [comment]
Or, you know, I could just merge and if somebody sees something broken they can damn well fix it themselves 😇

**Comment by dotcode** [comment]
Bit late to the party, but: excellent work @hollsk, top job.

**Pull request merged**
