### PR TITLE
add rationale for in-house style & change process

### PR DESCRIPTION
**Pull request by hollsk**
as per recent discussion in The Slack

### CODE REVIEW

**Comment by jpw** [comment]
So many 👍

**Comment by dotcode** [comment]
This is not specific to JavaScript

**Comment by hollsk** [comment]
I was going to put it somewhere else, but nowhere else really jumped out at me as a good location. Any suggestions?

**Comment by dotcode** [comment]
Actually … scratch that previous comment of mine. This rationale section needs to go in every file where we define a style, be it JavaScript or not. I think. What do you reckon?

**Comment by joseluisbolos** [comment]
I feel like quite a lot of the stuff in language/* is actually not specific to those languages and we should have a "code-standards.md" document somewhere.

**Comment by dotcode** [comment]
Yeah, I seem to remember having this feeling before. What do you reckon we commit this, then see if it would help to break some stuff apart in another PR?

**Comment by hollsk** [comment]
Yeah, sounds fair. I created #151 for that and I'll merge this one in.

**Pull request merged**
